server:
  port: 8020
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:password@discovery:8761/eureka/
  instance:
    hostname: ribbon